/**
 * Contains paths
 */
export const ROUTE_PATH = {
    HOME: '/',
    NOT_FOUND: '*',
    RESTAURANT_APP: '/restaurnt-booking-app',
    UI_KIT: '/ui-kit',
    DESIGN_SYSTEM_PRO: '/design-system-pro',
    DASHBOARD: '/dashboard',
    GLASSMORPHISM: '/glassmorphism',
    MULTIPURPOSE_TEMPLATE: '/multipurpose template',
    NOTIFICATIONS: '/notification',
    OVERVIEW: '/',
    PRODUCT_LIST: '/product-list',
    BILLING: '/billing',
    INVOICE: '/invoice',
    MESSAGES: '/messages',
    LOGIN: '/login',
    SIGN_UP: '/signup',
    DOCS: '/docs',
    COMPONENTS: '/components',
    HELP: '/help',
    ADJUSTMENTS: '/adjustments',
    GLOBAL: '/global',
    SETTINGS: '/settings',
    FACEBOOK: 'https://www.facebook.com/',
    GITHUB: 'https://www.github.com/',
    TWITTER: 'https://www.x.com/',
    DRIBBBLE: 'https://www.dribbble.com/',
} as const;
